### ISSUE TITLE
ListenerConversionsKt method for UpdatedPurchaserInfoListener

### ISSUE THREAD

**Issue by shimfish** [thisisthekap/Xamarin.RevenueCat.Android#20]
My understanding is that I need to use the ListenerConversionsKt methods for listeners like PurchasePackageWith().

However, there doesn't seem to be an easy way to set the UpdatedPurchaserInfoListener.

https://sdk.revenuecat.com/android/purchases/com.revenuecat.purchases.interfaces/-updated-purchaser-info-listener/index.html

Could/should this be added to ListenerConversionsKt?

**Comment by shimfish** [comment]
I see now that ListenerConversionsKt is actually part of RCs code. I thought it was a helper class that you added.

Oh well. Still can't work out how I should set up the UpdatedPurchaserInfoListener in C# then...

**Comment by shimfish** [comment]
Finally worked out that I just need to declare
```
public class DelegatingReceivePurchaserInfoListener : Java.Lang.Object, IUpdatedPurchaserInfoListener
{
        public void OnReceived(PurchaserInfo purchaserInfo)
        {
        }
}
```

Not being experienced in these things, I didn't realise I needed to inherit Java.Lang.Object to make this work.

**Comment by thisisthekap** [comment]
@shimfish You are welcome :)
