### ISSUE TITLE
C# examples of use?

### ISSUE THREAD

**Issue by BillFulton** [thisisthekap/Xamarin.RevenueCat.Android#36]
Hi. This looks really useful. Are there any C# code examples around? Thanks, Bill.

**Comment by thisisthekap** [comment]
Hi @BillFulton,

no, there are no specific C# code examples using this binding library. There are no plans to do so either.

Please refer to the docs given at https://docs.revenuecat.com/docs/configuring-sdk for details on how in integrate RevenueCat into your project. I am aware that there are no C# examples given, but as C# is quite close to Java in terms of Syntax, translating it should not be a big hassle.

**Comment by sjorsmiltenburg** [comment]
@BillFulton hi bill, did you manage to get it working? can you perhaps share some code samples?

**Comment by BillFulton** [comment]
Hi Sjors

I had to put it on the back burner for a while, but should be back into it next week. If I manage to discover how it works, I certainly will post. Hope you will do likewise - even small clues help!

Cheers
Bill

**Comment by sjorsmiltenburg** [comment]
please look at https://github.com/thisisthekap/Xamarin.RevenueCat.iOS/issues/21
I am currently working on the android part, and have made some improvements to the code already shared there.
I will provide an update when I am done with that.
