### ISSUE TITLE
provide convenience method for getCustomerInfo

### ISSUE THREAD

**Issue by sjorsmiltenburg** [thisisthekap/Xamarin.RevenueCat.Android#42]
getting the subscription status by calling getCustomerInfo is the most basic function everybody seems to need to use.
Somehow this is not provided by the PurchasesExtensions class
I thought to just use the Login method instead (since it also returns a CustomerInfo object as a result).
But a RC employee said I should not be calling this method multiple times.

Why is this method not provided? Do you use the same Login - replacement that I was using in your own code as well?

https://community.revenuecat.com/sdks-51/getting-an-expired-entitlement-but-also-item-already-owned-when-trying-to-purchase-2146?postid=6814#post6814

**Comment by sjorsmiltenburg** [comment]
on the iOS side I am able to use it as
await RCPurchases.SharedPurchases.GetCustomerInfoAsync();
So i'm a bit puzzled why I can't do the same on the android side.

**Comment by sjorsmiltenburg** [comment]
the same is true (the other way round) for the SyncPurchases method which is avaliable on Android, but not on the iOS side.

**Comment by thisisthekap** [comment]
@sjorsmiltenburg As you mentioned correctly, all the methods provided by the extensions project are just convenience methods. Therefore, you could call `Purchases.GetCustomerInfo` directly.

Contributions, which are adding convenience methods you miss are always welcome. If you need assistance on contributing, feel free to ping me on [Gitter](https://gitter.im).

**Comment by thisisthekap** [comment]
Fixed in #43
