### ISSUE TITLE
Current bindings not working for Xamarin.Android.Google.BillingClient version 5

### ISSUE THREAD

**Issue by sanjuleo** [thisisthekap/Xamarin.RevenueCat.Android#44]
Hi
As per Play store requirements, google billing client needs to be updated to minimum version 5. When I use billingclient 5 with Xamarin.RevenueCat.Android  version 5.3.0.3, it throws an error -
No virtual method queryPurchases(Ljava/lang/String;)Lcom/android/billingclient/api/Purchase$PurchasesResult; in class Lcom/android/billingclient/api/BillingClient; or its super classes (declaration of 'com.android.billingclient.api.BillingClient' appears in /data/app/~~zonVoIn7mBd2Q4MIbbZ6Vg==<App Name Redacted>-Xh27zzonD3CpupkD6B7ofw==/base.apk)'

Please advise ASAP as I am stuck with it.

Thanks

**Comment by CameronVetter** [comment]
Have you made any progress on this issue @sanjuleo ?

**Comment by sanjuleo** [comment]
Yes, I have created bindings for new version. Thanks.

**Comment by CameronVetter** [comment]
Would you mind doing a PR of those @sanjuleo ?

**Comment by malatx** [comment]
I need this as well. Actually I'm sure nearly 100% of people using this need it.

**Comment by CameronVetter** [comment]
> I need this as well. Actually I'm sure nearly 100% of people using this need it.

It turns out that this project is abandoned and the new bindings are in this one: https://github.com/thisisthekap/Tonestro.Maui.RevenueCat.Android

**Comment by malatx** [comment]
Ah, okay, thanks. That helps. But that package won't install into my Xamarin.Android project, and I am unfamiliar with "Maui" -- I guess I am forced to update everything to .net 7 just to use this package? @sanjuleo do you have bindings for RevenueCat 6 that work with Xamarin.Android, not only Maui?

**Comment by malatx** [comment]
I created a new bindings for RC 7.0.1 that does not require Maui.

**Comment by thisisthekap** [comment]
Fixed in https://github.com/thisisthekap/Xamarin.RevenueCat.Android/releases/tag/release-v7.0.1.3
