### ISSUE TITLE
Update to RevenueCat 3.5.0

### ISSUE THREAD

**Issue by thisisthekap** [thisisthekap/Xamarin.RevenueCat.Android#9]
Currently, Xamarin.RevenueCat.Android is binding to RevenueCat 3.4.1.

RevenueCat 3.5.0 is already available as stable release.

**Comment by thisisthekap** [comment]
Blocked by https://github.com/xamarin/java.interop/issues/728

**Comment by BitWizJason** [comment]
Good morning @thisisthekap . Looks like Xamarin resolved the blocking issue for this. Any chance you would be able to update both your Android and iOS RevenueCat plugins to 3.5.*?

**Comment by thisisthekap** [comment]
As Version 4 is going to have full API coverage is both Swift and objective C, I am planning to do the update once the first stable release of version 4 is available.

**Comment by BitWizJason** [comment]
@thisisthekap That makes sense. If it would help expedite things at all my company is willing to compensate you for your work and time.

**Comment by shimfish** [comment]
@thisisthekap Likewise willing to pay for work to get Android v5 release integrated. Desperately need the new Amazon support.

**Comment by thisisthekap** [comment]
Closed in favor of #32
